### ISSUE TITLE
Error: /articles/2/0/6/7/4/elife-20674-v1.xml could not be found

### ISSUE THREAD

**Issue by blahah** [codeforscience/sciencefair#120]
https://sentry.io/codeforscience/sciencefair/issues/304052017/

```
Error: /articles/2/0/6/7/4/elife-20674-v1.xml could not be found
  at notFound (/opt/ScienceFair/resources/app.asar/node_modules/append-tree/index.js:669:13)
  at apply (/opt/ScienceFair/resources/app.asar/node_modules/thunky/index.js:44:12)
```

**Comment by blahah** [comment]
@mafintosh the above error is being reported by a small number of clients. They are using the hyperdrive:`07e82e6ea1ab7e7c3d4872f035b2320e8aefe26ba35033b983f4b2e033d07d44`, which definitely has en entry for `/articles/2/0/6/7/4/elife-20674-v1.xml`.

Any suggestion as to why it would throw this error?

**Comment by blahah** [comment]
Note, this is only happening on linux clients

**Comment by mafintosh** [comment]
@blahah my guess is that you are accessing the hyperdrive archive at version 0 on linux sometimes. lets look at it tmw :)

**Comment by billbrod** [comment]
I'm having a similar issue whenever I attempt to download any article. I get the following:

```
/opt/ScienceFair/resources/app.asar/node_modules/raven-js/src/console.js:26 Content server serving /home/billbrod/Documents/sciencefair/datasources at 8000
/opt/ScienceFair/resources/app.asar/node_modules/fs-readstream-progress/index.js:19 Uncaught Error: /articles/0/5/2/4/1/elife-05241-fig1-v1-600w.jpg could not be found
    at notFound (/opt/ScienceFair/resources/app.asar/node_modules/append-tree/index.js:669)
    at /opt/ScienceFair/resources/app.asar/node_modules/append-tree/index.js:110
    at /opt/ScienceFair/resources/app.asar/node_modules/append-tree/index.js:362
    at /opt/ScienceFair/resources/app.asar/node_modules/append-tree/index.js:372
    at /opt/ScienceFair/resources/app.asar/node_modules/hypercore/index.js:120
    at apply (/opt/ScienceFair/resources/app.asar/node_modules/thunky/index.js:44)
    at _combinedTickCallback (internal/process/next_tick.js:80)
    at process._tickDomainCallback (internal/process/next_tick.js:128)
notFound @ /opt/ScienceFair/resources/app.asar/node_modules/append-tree/index.js:669
(anonymous) @ /opt/ScienceFair/resources/app.asar/node_modules/append-tree/index.js:110
(anonymous) @ /opt/ScienceFair/resources/app.asar/node_modules/append-tree/index.js:362
(anonymous) @ /opt/ScienceFair/resources/app.asar/node_modules/append-tree/index.js:372
(anonymous) @ /opt/ScienceFair/resources/app.asar/node_modules/hypercore/index.js:120
apply @ /opt/ScienceFair/resources/app.asar/node_modules/thunky/index.js:44
_combinedTickCallback @ internal/process/next_tick.js:80
_tickDomainCallback @ internal/process/next_tick.js:128
```

I get this for the jpg of every file in the image and for the xml file, as mentioned in the first post. I am running the Linux client (on Ubuntu 16.04 LTS). Has any progress been made on this?

**Comment by blahah** [comment]
Curiously, this paper and the associated data are missing from the original dataset. I am not quite sure how they came to be indexed in the dat, but subsequently removed and unavailable in the dat, but I will investigate.

**Comment by billbrod** [comment]
I've had this happen for every paper I've attempted to download, am I just incredibly unlucky?

**Comment by blahah** [comment]
@billbrod OK no that sounds like a different bug. Sorry for the poor experience. Investigating this now too!

**Comment by billbrod** [comment]
No problem, thanks for looking into it!
