### ISSUE TITLE
[v1.0.0 osx 10.10.1] TypeError: sodium.crypto_stream_xor_instance is not a function

### ISSUE THREAD

**Issue by blahah** [codeforscience/sciencefair#81]
## Description

App freezes with a black screen on startup on OSX 10.9 and 10.10.

## Details

https://sentry.io/codeforscience/sciencefair/issues/300109566/

```
TypeError: sodium.crypto_stream_xor_instance is not a function
  at Protocol._onopen (/Applications/ScienceFair.app/Contents/Resources/app.asar/node_modules/hypercore-protocol/index.js:283:32)
  at Protocol._onmessage (/Applications/ScienceFair.app/Contents/Resources/app.asar/node_modules/hypercore-protocol/index.js:311:17)
  at Protocol._parseMessage (/Applications/ScienceFair.app/Contents/Resources/app.asar/node_modules/hypercore-protocol/index.js:365:10)
  at Protocol._parse (/Applications/ScienceFair.app/Contents/Resources/app.asar/node_modules/hypercore-protocol/index.js:330:37)
  at Protocol._write (/Applications/ScienceFair.app/Contents/Resources/app.asar/node_modules/hypercore-protocol/index.js:238:8)
...
(3 additional frame(s) were not displayed)
```

This is an issue caused by `hypercore-protocol` trying to use a libsodium feature that is not yet available in `sodium-javascript`.

Relevant issues:

- https://github.com/mafintosh/hypercore-protocol/issues/15
- https://github.com/sodium-friends/sodium-javascript/issues/5

**Comment by blahah** [comment]
Fixed upstream - new build will automatically use the right version of `sodium-javascript`
